### ISSUE TITLE
Unhandled exception: Launcher crashes on load

### ISSUE THREAD

**Issue by ZacPJ** [Fris0uman/CDDA-Game-Launcher#36] opened 2022-10-07 04:06 UTC
* Description: When I try to open the launcher, it just gives this, I cant seem to reinstall the launcher either. I have made no personal changes to the launcher.
* Version: 1.6.1
* OS: Windows-10-10.0.19041-SP0 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'split'
* Traceback:
```
  File "cddagl\ui\views\main.py", line 1481, in showEvent
  File "cddagl\ui\views\main.py", line 3358, in refresh_builds
  File "cddagl\ui\views\main.py", line 3384, in refresh_changelog

```

**Comment by onura46** [comment] 2022-10-07 07:12
I can confirm this on version 1.6.2, as well.

```
CDDA Game Launcher version: 1.6.2
OS: Windows-10-10.0.19041-SP0 (64-bit)
Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'split'
Traceback:
File "cddagl\ui\views\main.py", line 1503, in showEvent

File "cddagl\ui\views\main.py", line 3380, in refresh_builds
File "cddagl\ui\views\main.py", line 3406, in refresh_changelog
```

**Comment by Fris0uman** [comment] 2022-10-07 08:18
My suspiscion is that right now ther is at least one merged PR in dda with a weirdly formatted description and the launcher can't handle it because I wasn't very smart in the way I coded it
It might solve itself once enough PR roll in to push that one out of the changelog.
I'll look into a proper fix this weekend

**Closed** 2022-10-08 13:45 UTC
