### ISSUE TITLE
Unhandled exception upon startup

### ISSUE THREAD

**Issue by ektoplazm** [Fris0uman/CDDA-Game-Launcher#38] opened 2022-10-10 17:11 UTC
* Description: launched the launcher
* Version: 1.6.2
* OS: Windows-10-10.0.19041-SP0 (64-bit)
* Type: `<class 'AttributeError'>`
* Value: 'NoneType' object has no attribute 'split'
* Traceback:
```
  File "cddagl\ui\views\main.py", line 1503, in showEvent
  File "cddagl\ui\views\main.py", line 3380, in refresh_builds
  File "cddagl\ui\views\main.py", line 3406, in refresh_changelog

```

**Comment by Fris0uman** [comment] 2022-10-10 18:46
Duplicate of #36 should have been fixed by #37 try the version 1.6.3 of the launcher

**Closed by Fris0uman** 2022-10-10 18:46 UTC
