### ISSUE TITLE
Save files deleted upon updating the game

### ISSUE THREAD

**Issue by Rjtheperson** [Fris0uman/CDDA-Game-Launcher#31] opened 2022-07-24 19:34 UTC
**Describe the bug**
My save files get deleted when I update to the latest version of the game.

**To Reproduce**
1. Open the launcher
2. Launcher shows save file available
![image](https://user-images.githubusercontent.com/65632694/180662791-8f922698-0a1b-449d-8083-921c22488326.png)
3. Update game
4. Upon launching the game, no world available to load
![image](https://user-images.githubusercontent.com/65632694/180662922-bba20ed9-8df2-4726-991d-163c7896e5ef.png)

**Expected behavior**
Save data should not disappear after every update.

**Screenshots**
Provided above

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 7

**Additional context**
I am now backing up my save files every time I close the game.

**Comment by Fris0uman** [comment] 2022-07-31 09:20
I can't reproduce this, just tried to use launcher > update game > press launch game and the save are just there

**Comment by RDru** [comment] 2022-09-19 10:05
@Fris0uman 
It is caused by "Do not copy or move the save directory" checkbox. 
I don't want to move my save because it's taking a long time. One of my previous playthroughs was more than 1GB so if you could fix this I would be grateful :)

**Comment by Fris0uman** [comment] 2022-09-26 14:11
Yes, that's what the setting means, but I guess the launcher could just ignore the save folder entierly

**Comment by ektoplazm** [comment] 2022-09-26 22:09
I'm pretty sure it worked the other way around? I've been playing cdda with both remyroy's and previous versions of your launcher for the past 3 years and this setting used to leave the save files in the base directory, with the setting unchecked the launcher copied the folder to the "previous version", which led to longer update time with large save files.

**Comment by ProvoGo** [comment] 2022-10-08 16:43
i just had a scare with my save files not showing up either with the do not copy or move the save directory setting turned on

after being used to another cdda launcher where that setting worked differently it was truly quite scary xD

**Comment by ektoplazm** [comment] 2022-11-15 23:24
just found out that updating the game twice in a row actually deletes all the saves if you have "delete instead of moving to trash" unchecked

**Closed** 2022-12-18 15:15 UTC
